src/Control/UAV/Ardupilot/Task.cpp
Now sends a takeoff command, rather than a mission packet. This command is handled when the copter is in Guided mode.
=> Control/UAV/Ardupilot: Changed behaviour of Copter takeoff. 

etc/auv/simulator.ini, src/Simulators/VSIM/Task.cpp
=> Simulators.VSIM: Accept GpsFix.cog as forced yaw input.

src/Control/UAV/Ardupilot/Task.cpp
Used for direct control of acceleration. Requires patch to arducopter firmware.
=> Control/UAV/Ardupilot: Consumes DesiredControl for acceleration setpoints for arducopter.

src/Transports/UDP/Task.cpp
Hi,
We needed this when working on cooperative systems. We had set up a seperate UDP transport between the vehicles with static destinations. 
Disable dynamic nodes: This issue was related to communicating with different GCSs, as they would subscribe to this node instead of the full transport task. 
Only local messages: When the vehicles were sending and receiving the same type of message, a loop would occur. This flag forces the task to only forward local messages. 
Any comments? The most critical part is the second issue, the first one might be circumwented by disabling announcing. (The issue appeared when connecting with Matlab afair)
Kristian
=> Transports/UDP: Added options for disabling dynamic nodes and only sending messages from local system

etc/x8-radiocomms.ini, src/Transports/SatComms/HumSat.hpp, src/Transports/SatComms/HumSat_Utils.cpp, src/Transports/SatComms/HumSat_Utils.hpp, src/Transports/SatComms/RadioMsg.hpp, src/Transports/SatComms/SatLink.hpp, src/Transports/SatComms/Task.cpp
This new feature will allow the vehicles to communicate with a satellite, using a new hardware (the HumSat radio).
The task works by:
1. Locate the satellite - to see if it is available to receive the transmission;
2. Consume messages - which are chosen by the user;
3. Treat the messages - the radio can only send a maximum of 32 bytes in each message;
4. Send each message to the radio and ask it to transmit it
The communication with the radio is an adaptation of files given by Vigo (the owners of the radio).
There are several points that need to be discuss with them (marked with a comment `// !!!!WRN:`).
Since to run the task there needs to be user intervention (and hardware), there is some code added or commented to make it run without the user or the radio (also marked with `// …
=> Transports/SatComms: Initial commit of new task.

src/DUNE/Parsers/Config.cpp, src/DUNE/Parsers/Config.hpp, src/DUNE/Tasks/Task.cpp
When the user changes system configurations, the configuration structured used to generate Config.ini is updated accordingly.
=> Dune/Tasks/Task: Update config whenever SetEntityParameters is received.

src/DUNE/Parsers/Config.cpp, src/DUNE/Utils/String.cpp, src/DUNE/Utils/String.hpp
Example: "Transports+ = AcousticLink, HistoricData"
=> DUNE/Parsers/Config: Allow appending to previously defined values.

CMakeLists.txt
Hi,
We wanted to have a core-folder in user/ as well, like the global scope files in src/DUNE. 
This attempt works, but I'm no expert in cmake. Especially the install-part needs some work I believe. 
Could someone take a look at it?
For a test user/ directory, you can use this: https://github.com/krisklau/dune-ntnu/tree/feature/user_DUNE
Thanks for the inputs :)
Regards,
Kristian
=> Adding a core-folder for the user space

src/Vision/FireMapper/MorseImageGrabber.h, src/Vision/FireMapper/Raster_Reader.cpp, src/Vision/FireMapper/Raster_Reader.h, src/Vision/FireMapper/Raster_Tile.cpp, src/Vision/FireMapper/Raster_Tile.h, src/Vision/FireMapper/Task.cpp
- Compression of fire maps to reduce their size
- IP and port parameters of the morse simulation server
=> Firemapper update

src/Vision/FireMapper/Mapping.cpp, src/Vision/FireMapper/MorseImageGrabber.h, src/Vision/FireMapper/Raster_Tile.cpp, src/Vision/FireMapper/Task.cpp
- Wrong time in firemaps
- Segfault fix
=> Firemapper bugfixes

src/Control/UAV/Ardupilot/Task.cpp
See https://github.com/LSTS/dune/issues/173
=> Control/UAV/Ardupilot: fixed bug in down velocity

src/Simulators/VSIM/Task.cpp
Simulation with dynamic currents works correctly now.
=> Simulators/VSIM: Fix stream speed integration

src/DUNE/Math/Matrix.cpp, src/DUNE/Math/Matrix.hpp
Hi, I've got two suggested changes to the matrix library. One is already an open pull request (#138), but I'm closing that one in order to gather these related changes here.
1. Make the identity matrix constructor explicit (discussion in #138).
2. Make the diagonal matrix constructor take a const pointer (similar to my earlier, merged PR #117).
=> Math::Matrix fixes

src/Control/UAV/Ardupilot/Task.cpp
As discussed in the previous sync meeting @mariacosta
=> Control/UAV/Ardupilot: Only change to GUIDED if not in GUIDED

src/Control/UAV/Ardupilot/Task.cpp
=> Control/UAV/Ardupilot: Made "Seconds before Waypoint" float

src/Control/UAV/Ardupilot/Task.cpp
by adding DF_KEEP_TIME
See #183, courtesy @krisklau 
Should be a no-brainer to merge
=> Control/UAV/Ardupilot: Fix acc/angvel/mag timestamp

src/DUNE/Hardware/PWM.cpp, src/DUNE/Hardware/PWM.hpp
As discussed with @mariacosta and @zepinto 
We have used this quite a bit on the BBB
=> DUNE/Hardware/PWM: class for interfacing with HW PWM

src/Control/UAV/Ardupilot/Task.cpp
Calculate wp distance in locally, instead of relying on distance reported by AP, as this might not be updated to the next WP after a previous WP has been accepted. This sometimes caused two consecutive WPs to be accepted "simultaneously". 
The commit also logs crosstrack error from AP in PathControlState and checks m_changing_wp (bool) rather than m_last_wp (float).
As discussed in the previous sync meeting, @mariacosta
=> Control/UAV/Ardupilot: improve wp switch logic

src/Navigation/AUV/Navigation/Task.cpp
Fixed initialization of `m_speed_model` pointer. Function
`onResourceRelease` is called after construction so an uninitialized
pointer was being deleted.
According to the standard (5.3.5 [expr.delete] / 2):
```
In the first alternative (delete object), the value of the operand
of delete may be a null pointer value, a pointer to a non-array
object created by a previous new-expression, or a pointer to a
subobject ([intro.object]) representing a base class of such an
object (Clause [class.derived]). If not, the behavior is undefined.
```
=> Navigation/AUV/Navigation: initialize pointer to fix undefined behavior

src/DUNE/Navigation/UsblTools.hpp
- Added Luis Venancio as author
- Initialize member variables when possible in the initializer list
- Use range-for loops where applicable
- Removed unneeded 'void' from empty function call
- Added const qualitifier to member functions where applicable
- Filter's Math::MovingAverage can be placed in the stack
=> DUNE/Navigation/UsblTools: modernize the code plus a few minor changes.

src/DUNE/Math/General.hpp
Fix for issue [#241](https://github.com/LSTS/dune/issues/241).
=> DUNE/Math/General: Fix average calculation
