- src/Control/UAV/Ardupilot/Task.cpp
(New PR that do not include the new mavlink definitions...)
> Control/UAV/Ardupilot: In handleArdupilotData, added three new known message ids. (IMU_SCALED2, AHRS2 and TERRAIN_REPORT)

- cmake/Libraries/Phidget.cmake
Phidget is a USB-based sensor board, useful for fast-prototype sensor applications. 
(With some minor changes to Glued, it works and is tested on the beaglebone. This PR will come later. )
> cmake/Libraries/Phidget: Added support for Phidget

- src/Control/UAV/Ardupilot/Task.cpp
- src/Monitors/Medium/Task.cpp
This PR uses the right fields from mavlink to set Height, and also sets the altitude field in EstimatedState. 
The altitude is now used for medium-detection. The previous way it was done was not really valid. (NB: In Monitors/Medium; the altitude value is only used for copter. FW checks airspeed).
> Control/Ardupilot: Proper handling of ArduCopter Height

- src/Transports/Seatrac/Task.cpp
Hello,
Just wanted to let you know that to compile Dune in Windows Visual Studio you have to add to the Transports.Seatrack Task "#include ".
Otherwise you get an error std::back_inserter
Just a heads up.
Regards,
André
> Fix compilation error in Windows Visual Studio.

- src/Control/UAV/Ardupilot/Task.cpp
See previous discussion in https://github.com/LSTS/dune/pull/49 :) 
This PR makes the ardupilot task dispatch a new message, ExternalNavData. Further, the new navigation task consumes this data and dispatches the EstimatedState message. The navigation task can choose to also utilize data from other sources, such as RTK. 
Message-definitions can be seen here: https://github.com/LSTS/imc/pull/9
(some cleanup and testing still needed)
> Control/Ardupilot: Enable external navigation data for Ardupilot. [now ready, previously WIP]

- src/Control/UAV/Ardupilot/Task.cpp
Concerning "Control/UAV/Ardupilot: Force setup of rates if lost connection due to timeout.", is very useful when the pixhawk is restarted but not Dune (might happen during battery change)
> Control/Ardupilot: Various Ardupilot fixes

- src/DUNE/Control/BasicUAVAutopilot.hpp
Fixed bug where delta timer was not reset on activation, leading to a situation where the delta time was calculated from the previous time the controller was used.
> DUNE/Control/BasicUAVAutopilot: Fixed bug

- programs/generators/imc_code.py
It is automatically upcasted if necessary. Removes the need for a static_cast<DerivedType*>(...).
> Return cloned IMC message object as derived type.

- src/DUNE/Control/PathController.cpp
- src/DUNE/Control/PathController.hpp
If the user / planner commands a point too far away (> 25Km by default), the path controller goes into error mode ("track length too long").
> DUNE/Control/PathController: Check track length.

- cmake/Version.cmake
If cmake is run repeatedly (e.g in an automatic build process), the Version.cpp file causes a re-linking to occur for dune-core every time. Only writing an empty Version.cpp file if it does not already exist resolves this, and allows the [comparison](https://github.com/LSTS/dune/blob/a016911e92eb7c96b590a652d11b1e230f1066a8/cmake/Version.cmake#L66) to work as intended. This comparison currently compares an empty file to the previous file, and will always recreate Version.cpp, thus causing a rebuild of dune-core and re-linking of external projects.
My last pull request failed because the file must exist for the build to succeed.
> Remove the need for a rebuild of dune-core on cmake generation

- src/Maneuver/FollowReference/AUV/Task.cpp
Since the path_ref field is not checked in this comparison, the state machine can wrongfully enter loiter/elevator/hover ([link](https://github.com/LSTS/dune/blob/d7a7c8e3867ed98dfa7334cc577268630852dfe3/src/Maneuver/FollowReference/AUV/Task.cpp#L351)) or set the XY_NEAR flag ([link](https://github.com/LSTS/dune/blob/d7a7c8e3867ed98dfa7334cc577268630852dfe3/src/Maneuver/FollowReference/AUV/Task.cpp#L399)).
The race condition occurs if the path control state of the previous waypoint is received after switching to a new waypoint. The check for still_same_reference mitigates the problem, but it can still occur if the references are sent often. I encountered this when the path controller was implemented externally (e.g over a network).
> Fix possible race condition

- src/DUNE/Math/Matrix.cpp
- src/DUNE/Math/Matrix.hpp
This a) is more const-correct and b) it allows initialization based
on both const and non-const arrays. If you have something like
```c++
const double data[3] = {1.0, 2.0, 3.0};
```
you can now do
```c++
DUNE::Math::Matrix m(data, 3, 1);
```
which was previously impossible when `data` was a const array.
> Use const data array in Matrix constructor

- src/Transports/Replay/Task.cpp
This is pretty small so I'm just creating a PR directly without an issue.
Fixes entity assignment issues when replaying more than one log using the Replay task:
Entity maps `m_name2eid`/`m_eid2name` are created during the startup of the Replay
task, in `onEntityReservation()`, but they get cleared each time a log being
replayed finishes. When replaying more than one log (or one log several times)
that gives undefined entity IDs after the first replay. Leaving the entity maps
intact even when `reset()` is called solves this.
> Transports/Replay: Avoid clearing entity maps when resetting

- src/Plan/DB/Task.cpp
There's currently no reply for DSTATE requests. The simple plandb requests returns the full plan information in the plans_info field instead of being empty, contrary to the description in IMC (DBOP enumeration). The original intent for the simple state request cannot be implemented at this point without breaking external code.
This pull request adds identical behaviour for both STATE and DSTATE. An alternative to this pull request is to remove the DSTATE enumeration from IMC, as it is likely to be unused so far given the lack of a DUNE implementation. Personally, I think the latter is the better solution, unless the IMC STATE/DSTATE behavior is going to be implemented at some point.
> Plan/DB: Add reply to detailed PlanDB request.

- src/DUNE/Control/PathController.cpp
- src/DUNE/Control/PathController.hpp
it can be overloaded in controller specific implementations
As discussed in #93 
I also had to add get-functions for m_time_factor and speed, to make them available in the child pathControllers. Can of course change this to parameters to the getEta function, but I thought this approach was cleaner and easier to extend.
> DUNE/Control/PathController: made calculation of ETA a function, so that

- src/Transports/UDP/Task.cpp
We are using this for an automated feature to enable inter-vehicle IMC communication. By setting a seperate Transports.UDP task up with a custom service, e.g. intervehicle_formation, other vehicles can search for this feature and send specific messages to this vehicle without hardcoding remote IP's in static destinations.
> Transports/UDP: enable optional custom service type

- etc/x8-06.ini
- src/Simulators/UAV/Task.cpp
For the simulation profile, set the default wind to 0 and allow to set it with WindSpeed messages
> Simulators/UAV: Consume WindSpeed messages to set simulator wind

- src/DUNE/Math/Matrix.cpp
- src/DUNE/Math/Matrix.hpp
I think the unary minus operator should be made const. Otherwise, stuff like this will not compile:
```c++
const Matrix a(3);
Matrix b = -a;  // operator- is not a const method, and cannot be called on a const object
```
> DUNE/Math/Matrix: Make operator- a const method

- src/DUNE/Hardware/GPIO.hpp
GPIO objects should not be possible to copy. This PR fixes that.
Most people wouldn't do
```
GPIO g1(1);
GPIO g2(g1);
GPIO g3 = g1;
```
but some fools such as myself might try to
```
std::vector<GPIO> v;
v.emplace_back(1);
v.emplace_back(2),
```
Both of these give only run time errors, but by disabling the copy constructor and copy assignment operators, we turn them into compile time errors. Much better!
> DUNE/Hardware/GPIO: Make GPIO class non-copyable

- src/DUNE/IMC/Bus.cpp
This seems to fix #151
Simultaneous access of shared memory from multiple threads. 
The bus is responsible for all the recipients of IMC messages. In this setting, we are focused on the mechanism to register a new task to the bus, through the method `registerRecipient`. 
https://github.com/LSTS/dune/blob/2a32fbe42d241bfa207681a75c46b69112c1bc65/src/DUNE/IMC/Bus.cpp#L81
This is called when a task issues a `bind<>` command. For most tasks, this is done at task object construction. 
The daemon thread constructs all tasks in its own thread, before any new threads are spawned. Thus, for the tasks issuing a bind in the constructor, we have no problems. 
After all tasks are constructed, the new task threads are spawned. Now enter the Logger task. At first start, it will try to start a new log …
> DUNE/IMC/Bus: Fix concurrency bug (caused segfaults)

- src/Control/UAV/Ardupilot/Task.cpp
One of the mavlink_message_t variables were defined as a pointer. I changed this to a normal variable (on the stack), like the other mavlink message variables. Have not noticed anything, but I guess this was a memory leak.
> Avoid use of (undeleted) mavlink message pointer

- src/DUNE/Maneuvers/Maneuver.hpp
Noticed a small mistake in the Maneuver base class method docstrings. Probably someone copied from another method and forgot to modify.
> DUNE/Maneuvers/Maneuver: Correct wrong method docstring

- src/Transports/Seatrac/Task.cpp
Fixed segfault in Seatrac Task because ticket pointer is not initialized.
The src/Trasnports/Seatrac/Task.cpp has a member variable Ticket* m_ticket.
However, that point is not initialized to NULL. This causes a segfault on
some systems in sendTxStatus(...) because the ticket is used without being
initialized. Normally, the check for NULL in clearTicket(...) would have
prevented this from happening.
Fixes #189.
> Fixed segfault in Seatrac Task because ticket pointer is not initialized

- CMakeLists.txt
- src/DUNE/Coordinates/WGS84.hpp
Refers to original PR #144, by @krisgry 
Added ellipsoidal coordinate system as compilation option.
> Optional more accurate displace for WGS84

- src/DUNE/IMC/MessageList.hpp
This is just a tiny nice-to-have change. Most STL containers have both a `size()` and an `empty()` method, but `IMC::MessageList` only has `size()`. Many programmers are used to having an `empty()` method on container-like classes, so I've added `IMC::MessageList::empty()` for convenience.
Lets you do stuff like
```cpp
void consume(const IMC::Distance* msg)
{
if (msg->location.empty())
{
war("IMC::Distance location undefined");
}
}
```
instead of for instance
```cpp
void consume(const IMC::Distance* msg)
{
if (msg->location.size() == 0)
{
war("IMC::Distance location undefined");
}
}
```
which is somewhat uglier.
> DUNE/IMC/MessageList: Add empty() method

- src/Control/UAV/Ardupilot/Task.cpp
Previously, m_hae_offset would be reset to zero if a single GpsFix message indicated poor Gps conditions, and since it did not reset the m_offset_st flag, it would remain zero forever, causing the "WGS84 height" in DUNE to be equal to MSL. Now, the offset is only set to zero if the conversion flag is false, in which case m_offset_st is also reset to false. If Gps is lost, the old value of the offset is used.
The debug-printouts are of course not needed, but proved useful when debugging this.
Hopefully this is the end of the AP/DUNE height issues. This has been tested in flight.
> Control/UAV/Ardupilot: Ensure hae_offset is not reset upon losing GPS fix

- programs/generators/imc/utils.py
Update IMC Generator utils to create MD5 on RHEL
RHEL prevents the use of MD5 sum for security purposes.
The programs/generators/imc/utils.py calls hashlib.md5(),
which fails. RHEL requires hashlib use the
usedforsecurity=False option.
Fixes #187.
> Update IMC Generator utils to create MD5 on RHEL.

- src/Control/UAV/Ardupilot/Task.cpp
The data output from the Ardupilot task is not scaled correctly. This has been confirmed by both data from SITL and physical flights (see the below picture), and is fixed by this commit.
> Control/UAV/Ardupilot: fixed scaling of raw IMU data

- etc/lauv-nemo-1.ini
- src/Simulators/CDC3/Task.cpp
Updated CDC3 Simulator to support sending Target-of-Interest messages.
Updated CDC3 Simulator to support sending Target-of-Interest messages. Also
update the lauv-nemo-1.ini file to include the option for the TOI period.
Fixed #191.
> Updated CDC3 Simulator to support sending Target-of-Interest messages

- etc/testing/replays/sgnav-replay.ini
- src/Transports/Replay/Task.cpp
Added functionality to skip the initial <skip> seconds of a log replay, inspired by dune-lsfreplay. This is done by simply looping through the messages in the log file, until the difference between timestamp of the message and the start of the log is larger than the desired number of seconds to skip. While looping through messages, EntityInfo messages are handled, to build a map of the Entities.
This has been tested, and works for the functionality that I needed, but perhaps there is something I've missed?
> Skip initial part of replay

- src/DUNE/Tasks/Task.hpp
Say you have two tasks that both dispatch the same IMC message type, and some other tasks that consume those messages. The consuming tasks must then choose which source entities they want messages from. I've been thinking about making a new base task class, that inherits `DUNE::Tasks::Task`, and implements a new method maybe called `filteredBind` that automatically sets up a filter on incoming message source entity. This requires me to use a custom consumer class, which means I need access to `bind(unsigned int message_id, AbstractConsumer* consumer)` so I can call it with my custom consumer.
An alternative would be to add this `filteredBind` directly to `DUNE::Tasks::Task`, but I think making `bind(unsigned int message_id, AbstractConsumer* consumer)` protected is a better solution, …
> Make Task::bind protected (instead of private)

- src/DUNE/Maneuvers/StationKeep.cpp
- src/DUNE/Maneuvers/StationKeep.hpp
These patches fix two bugs in the `StationKeep` class which cause `PathController` to timeout during execution of the `StationKeeping` maneuver.
* 6bc18fe - Set the `FL_DIRECT` flag in the `DesiredPath` message dispatched by the `StationKeeping` maneuver. This forces the `PathController` to use the estimated position of the vehicle as the path starting point. Otherwise the `PathController` will sometimes set the endpoint of the previously received path as the starting point for the new path, which in the case of `StationKeeping` leads to a path with identical start and end points.
* 6ec7dd4 - `PathControlState` messages with `FL_NEAR` set must not be ignored, or else `PathController` will timeout while waiting for a new reference. The `DesiredPath` message must be re-sent. The rate at …
> Fixes in DUNE/Maneuvers/StationKeep

- src/DUNE/Control/BottomTracker.cpp
- src/DUNE/Control/BottomTracker.hpp
- src/DUNE/Control/PathController.cpp
Enforce a minimum depth limit when tracking altitude references.
> BottomTracker: Add minimum depth option

- src/Simulators/AcousticModem/Driver.hpp
- src/Simulators/AcousticModem/Task.cpp
Member variable `m_current_op` was being dereferenced inside `run`
call without being properly initialized.
> Simulators/AcousticModem: initialize m_current_op

- src/Supervisors/Vehicle/Task.cpp
Small enhancement that might be valued by others than me.
My use case: I have multiple tasks that monitor different aspects of a landing maneuver, and each of them will issue an Abort if their abort criteria is fulfilled.
> Supervisors/Vehicle: also show who requested an abort

- src/Maneuver/FollowReference/UAV/Task.cpp
Found a copy-paste error in FollowReference/UAV, see the diff: did not set start_z, but set start_lon twice
> Maneuver/FollowReference: fix start z

- src/Transports/Logging/Task.cpp
If the transports parameter is not set (default value is empty), Tranports.Logging will now log all IMC message types.
> Transports/Logging: Log all messages when Transports parameter is empty.

- etc/development/novatel.ini
- src/Sensors/GPS/Task.cpp
This PR modifies the current GPS task to take advantage of the SBAS funcionality provided out of the box in most Novatel GPS receivers. This is configured through a parameter called `Novatel SBAS`.
Included is also an example configuration file, which was successfully tested against the Novatel FlexPak6 (OEM6).
> Sensors/GPS: Add Novatel SBAS support

- src/DUNE/Hardware/SerialPort.cpp
- src/DUNE/Hardware/SerialPort.hpp
Small PR to make it possible to use the SerialPort interface in read-only mode. Work by Artur Zolich.
Also have some code that makes use of this in SerialOverTCP, but that code is a bit "brute force". Just mentioning it, in case someone is interested.
The use-case was: two UHF radios on the ground, and wanted to be absolutely sure that only one of them was sending data.
> DUNE/Hardware/SerialPort: add read-only option

- src/Transports/CommManager/Router.hpp
- src/Transports/CommManager/Task.cpp
Messages were being cloned (new) without being properly released.
- Avoided cloning where possible
- Release resources
- Make sure order of deleting pointers and erasing elements from
container is correct
> Transports/CommManager: fix several serious and continuous leaks
